---
title: "testings"
author: "JJ"
date: "March 2, 2015"
output: html_document
---


```{r}
confmatrix <- as.conflictmat(SampleEdgelist)
path.output <- IDpaths(conf = confmatrix, ID = 35281, len = 2)

# fix path.output
for (i in 1:length(path.output)){
  path.outdf[i] <- row.names(confmatrix)[path.output[i]]
}

countPaths(path.output) # return errors: incorrect number of dimensions

countPaths = function(allPaths){
  nOrders = length(allPaths)
  pathList = list()
  N = max(sapply(allPaths, max))  #! sapply needs to be fixed; why do we need N here?
  
  for(K in 1:nOrders){
    pathList[[K]] = as.conflictmat(allPaths[[K]][,c(1,(K+1))]) #! return error:"Error in a[[1]][, c(1, (1 + 1))] : incorrect number of dimensions"
  }
  pathList
}


nOrders = length(path.output)
pathList = list()
N = max(sapply(path.output, max))
a <- as.data.frame(path.output)
a[1][,c(1,2)]
path.output[[1]][,c(1, 2)]
path.output[1]

allPaths = list(
      which(confmatrix > 0, arr.ind = TRUE),
      do.call(rbind, sapply(1:N, function(k){IDpaths(confmatrix, k, 3)})))
      
allPaths      


transitivity(confmatrix)


plot.conf.mat(confmatrix)
```

You can also embed plots, for example:

```{r, echo=FALSE}
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
